### ISSUE TITLE
Subclassing RunebergVR-Pawn leads to compile errors

### ISSUE THREAD

**Issue by mhaemmerle** [1runeberg/RunebergVRPlugin#10]
When I create a new C++ Class in the UE4 Editor and select the RunebergVR_Pawn as parent, the Editor (and Visual Studio) fails to compile.

Tried this via installed Plugin as well as just copying the Plugins-directory to my project.

I'am using Master of the plugin and UE4 4.16.1

Here are the resulting compile errors (I removed the base-path from the log):

CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(35) : error C2143: syntax error: missing ';' before '*'
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(35) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(35) : error C2238: unexpected token(s) preceding ';'
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(43) : error C2143: syntax error: missing ';' before '*'
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(43) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(43) : error C2238: unexpected token(s) preceding ';'
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(35) : error C2143: syntax error: missing ';' before '*'
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(35) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(35) : error C2238: unexpected token(s) preceding ';'
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(43) : error C2143: syntax error: missing ';' before '*'
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(43) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
CompilerResultsLog:Error: Error REMOVED\Unreal Projects\VRTest\Plugins\RunebergVRPlugin\Source\Public\RunebergVR_Pawn.h(43) : error C2238: unexpected token(s) preceding ';'

**Comment by 1runeberg** [comment]
HI Marc - Have you tried removing your Binaries, Intermediate and Build folders both in your project AND under Plugins\RunebergVRPlugin\ ?

I've tried replicating the issue but I'm unable to from my end using 4.16.1 & VS2015

**Comment by mhaemmerle** [comment]
I did that but can't open the project in UE4 anymore, as it fails to build the project code. Building in VS2015 also fails with the previously posted compile errors.

Maybe I'am missing something? Or the way I extend the VR pawn is wrong (default CTOR)? I'am new to both C++ and UE4...

Packaged the project and will attach it to this comment.

[VRTest.zip](https://github.com/1runeberg/RunebergVRPlugin/files/1098345/VRTest.zip)

**Comment by 1runeberg** [comment]
Hi Marc,

Thanks for the files. Some component dependencies seem to break when you subclass it so I've added explicit includes as a safety in RunebergVR_Pawn.h to help correct, you can download the latest copy with the hotfix here in GitHub or add the following lines in RunebergVR_Pawn.h:

`...`
`#include "Components/CapsuleComponent.h"`
`#include "Camera/CameraComponent.h"`
`...`

Let me know if you continue to have issues with this.

**Comment by mhaemmerle** [comment]
Thanks, this fixed it for me.
