### ISSUE TITLE
Wrong location at BeginPlay when using a Rift

### ISSUE THREAD

**Issue by dukfaar** [1runeberg/RunebergVRPlugin#11]
In ARunebergVR_Pawn::BeginPlay() you do the following (when using a Rift):
`this->SetActorLocation(FVector(0.f, 0.f, this->GetActorLocation().Z + 150.f));`
That way, your PlayerStart settings get ignored and you always start at (0, 0, Z+150).

Something along the lines of
`this->SetActorLocation(this->GetActorLocation() + FVector(0.0f, 0.0f, 150.0f));`
should fix that. I think, all you wanted to do there, is an offset, right?

**Comment by 1runeberg** [comment]
Hi Robert - Thanks for the feedback - good catch! Yes, that's indeed an oversight from my end. 

I'm due to release version 2.6 this evening or the latest tomorrow morning with a couple of new features, will add this  fix in there incl. automating the origin of the HMD.

Cheers,
Rune.

**Comment by 1runeberg** [comment]
Hi Robert, new version (2.6) which includes this fix is already up here in GitHub... Marketplace version update to follow in a couple of days.

Any further questions on this, please just let me know.

Cheers and Thanks again!
Rune.
