### ISSUE TITLE
How to rotate pawn while teleporting

### ISSUE THREAD

**Issue by myasir2** [1runeberg/RunebergVRPlugin#15]
Hi,

First I must say that great plugin! I do have a question which is how can i control the rotation of the pawn while teleporting? I'm not sure if this is already a built-in feature of the plugin but I am pretty new to this so if it is, can you please show me how to "turn it on". If not, can you maybe give some advice on how can i control the rotation of the pawn while teleporting?

Thanks!

**Comment by 1runeberg** [comment]
Hi! Thanks for the feedback. you can use the standard Blueprint node "Reset Orientation and Position" to do this.
