### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by juangauthier** [1runeberg/RunebergVRPlugin#2]
Hello!
Great work on the plugin!! got it running in minutes.
One question though...
Is it possible to change the way the grabbing of objects works?
Right now when i grab an object it somehow "snaps" into the vivemesh pivot location, and i wonder if its possible to make the grabbed object to attach where i pointed with the controller?
Example: if i grab a chair by the leg i would lift it holding the leg.

Thanx in advance!
Juan

**Comment by 1runeberg** [comment]
Hi Juan! Thanks... Yeah , good idea - will add that in the next release hopefully in a week or so... it will come up here in github first. The UE4 marketplace version a week or so later after that as the modifs go through Epic code checks. Cheers.

**Comment by 1runeberg** [comment]
Hi Juan!

I've made a new component to this plugin - "SimpleGrabber", this is separate from the original (ranged) "Grabber" component and can do precision grabs.

Will make a couple of vids to explain this new SimpleGrabber component and new stuff in the original Grabber.

Enjoy!
