### ISSUE TITLE
destructible object idtype

### ISSUE THREAD

**Issue by juangauthier** [1runeberg/RunebergVRPlugin#3]
hello!
great work as usual with the latest update! 
another question:

if i want to pickup a destructible object, am i wrong to assume that i can do the same way as with the physical object to be able to grag them but add another grab function but set the object type id for destructibles so i can grab them but when released the fall appart in chunks? in that case, which id corresponds for the destructibles?

**Comment by 1runeberg** [comment]
Hi Juan! 

Are you referring to the new simplegrabber component? with the simoplegrabber, by default, anything that has collision set to physics actor and has generate overlap events toggled will be "grabbable".

you only need an object type/collission channel if you want to be more "selective" of which actors in your scene can be grabbed.  As long as you toggle "Enable Physics" in the "Release" function your destructibles should also work as normal.

let me know if that helps or if I misunderstood your question.

**Comment by 1runeberg** [comment]
Configurable object types now avaliable in Update 3.0
