### ISSUE TITLE
4.15 update

### ISSUE THREAD

**Issue by juangauthier** [1runeberg/RunebergVRPlugin#6]
Hello!
Is there any chance that the RunebergVRPlugin will be updated to 4.15?

Juan

**Comment by mi7flat5** [comment]
I don't really know, I'm only watching this repo, but I don't think it will
be difficult to do, and the plugin on the asset store is from this repo.
They update it pretty regularly.

**Comment by 1runeberg** [comment]
hi guys... sorry, got busy at work -- will be updating this either tonight or tomorrow. Here in GitHub first then submitting to Epic for review/publication of the update in the Marketplace.

**Comment by 1runeberg** [comment]
Updated to 4.15 - please let me know if you have any issues with the new version. Marketplace update submitted to Epic for review, should be up there soon!
