### ISSUE TITLE
Menu for VR

### ISSUE THREAD

**Issue by jaydehei** [1runeberg/RunebergVRPlugin#8]
Hi there Rune,

Already said it to you in a previous mail, great work, thanks for making VR easier to use :) !
(studying Unreal and blueprints quite hard these months, but still pretty new with some mechanisms, so pardon me if some issues may be unclear or due to my lack of knowledge.)

I'm trying to build just a classic pause menu for VR, using UMG tools in Unreal. I searched for tutorials, but found nothing that helped me clearly...I managed to build a UMG menu I displayed permanently on screen, and that is motion-controller-clickable, so that's quite good.
Problem is I want to display this menu just in front of the player, whenever he pushes a button (and if that's possible, putting a low opacity color to hide what's on screen). I can't find a way to display it right in front of where the player first pushed and where he was looking at...I tried to get the world location and rotation of the camera, but still didn't change a thing, the menu keeps displaying at the same place and rotation no matter what.
Another issue I had is how to display the UMG menu (currently a blueprint containing a Widget) in front of the world geometry...as the world remains active when I try to display the menu, some parts of the world (objects, walls, etc) can hide the menu too...
Hope my questions were clear enough :/

Any ideas, suggestions, or links to tutorials are welcome, thanks :)

**Comment by 1runeberg** [comment]
Hi Jay!

Thanks, glad you found it useful.

If you're using the plugin's VR Pawn, the camera location and rotation should be correct, depending on how your menu system is setup, the actor may need to be rotated to face the player using the "Find Look At Rotation" blueprint node. Or you can of course use the HMD function (orientation and position if positional tracking is available in the user's device): (https://docs.unrealengine.com/latest/INT/Platforms/VR/ContentSetup/#headmounteddisplayblueprintnodes)

I'm not sure it's a good idea to "blur" the scene in a VR game, check out the following Oculus best practice guideline (look at the User Interface section for some tips on how to implement a good VR UI which should avoid some of the pitfalls you are currently facing):
https://static.oculus.com/documentation/pdfs/intro-vr/latest/bp.pdf

Hope that helps.

**Comment by jaydehei** [comment]
Thanks :) Menu is displayed at the right location and right orientation now, getting the rotation of the camera and a few adjustements was enough for that :)

Didn't know about these guidelines, I'll have an eye on these, thanks again :)
