### ISSUE TITLE
Teleport issue ?

### ISSUE THREAD

**Issue by jaydehei** [1runeberg/RunebergVRPlugin#9]
Hi again Rune,

Ran into another issue, I don't know if I'm doing it wrong or if if the plugin doesn't consider that...

So it's about teleporting depending on the room surface on HTC Vive. Let's say I set up my playground to a large 3m*3m room, and the VR game I'm in represents a small museum room. Then let's say I get physically to the angle of my 3m*3m room, then want to teleport next to one of the walls of the game...the "teleport now" considering I'm not at the center of my room will make me teleport not at the place I pointed at with my controller, but with a shift, so I'll possibly get behind the wall, or out of the navigation bounds...
I don't know if my explanations are clear ?

So do I need to manually recalculate the teleport point due to the shift, or is there already an option to avoid that ? And if I have to manually recalculate the teleport point, how could I get to it using the "teleport now" function as it doesn't take any parameters ?

(just a final question, when I attach a Runeberg_Teleporter to one of the motion controllers, and setting a teleport target mesh to it (let's say a cylinder to mark the teleport location), as it is attached, the cylinder will rotate the same way the motion controller rotates...so that's details, but dunno if that's an option you could add for the next versions ? again...maybe I'm doing it wrong, please tell me if I do)

And thanks again for your time answering my questions ! Hope it doesn't bother you...

**Comment by 1runeberg** [comment]
Hi Jay!

I'm not sure I understood your first question sorry - can you write me an email (ue-marketplace-support {at} runeberg {dot} io) with screenshots of the problem? The NavMeshBounds should take care of all the valid positions you have in your level, so you shouldnt need any additional offsets although the component does provide this feature too.

Regarding the marker rotation - yes, you are right, it's set to rotate to face the player -- will expose a custom rotation on the next update then :)

Cheers,
Rune

**Comment by 1runeberg** [comment]
HI Jay!

Thanks for the email and bug report. I've now fixed that Teleport Offset issue you described and you can now also do custom rotations of the target mesh including allowing hte pawn to follow this rotation after teleport.

It's currently in v2.4 here in GitHub and should be up in the UE4 Marketplace in a couple of days.

**Comment by jaydehei** [comment]
Thanks Rune :) 
Looking forward to see the next versions and features !

**Comment by 1runeberg** [comment]
More fixes in Update 3.0
